version: '3.8'

networks:
  default:

services:
  db:
    image: postgres:latest
    container_name: datajpa-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
  app:
    build:
      context: .
    image: local/datajpa:latest
    container_name: datajpa-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://datajpa-db:5432/postgres
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8080/actuator/health | grep -q '^{"status":"UP"' && exit 0 || (echo "failed";exit 1)
      interval: 10s
      timeout: 120s
      retries: 10
