version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: my_security_db
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-db
  mailer:
    image: mailhog/mailhog:latest
    container_name: my_mailer
    ports:
      - "8025:8025"
      - "1025:1025"