logging:
  level:
    org.springframework: debug

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bugtracker
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false

graphql:
  servlet:
    enabled: true
    exception-handlers-enabled: true
  graphiql:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, beans, mappings, configprops, conditions
  endpoint:
    health:
      show-components: always
      show-details: always
